spring:
  data:
    mongodb:
      auto-index-creation: true
      database: comfort_feeling
      uri: mongodb+srv://admin:sundo0528soft@comfortfeeling.zi0os.mongodb.net/comfort_feeling

  jpa:
    show-sql: true
    properties:
      hibernate:
        ogm:
          datastore:
            create_database: ture